// AUTO-GENERATED by scripts/generate_predictions.py — do not edit by hand.
// Source: the team notebooks (train 2022-2024, test 2025). Volume is not stored
// in Supabase, so the historical cloud and coefficients are cited constants here.

export type LinearEq = { a: number; b: number; rmse: number; mapeMonthly: number };

// Consumption (MWHr) = a + b * Volumen
export const ELEC_EQ: Record<"fundicion" | "norte", LinearEq> = {
  fundicion: { a: 1861.6576, b: 1.582400, rmse: 138.0, mapeMonthly: 2.56 },
  norte: { a: 1267.4305, b: 0.112206, rmse: 211.4, mapeMonthly: 3.05 },
};

// Fundicion water (M3) honest chain: Volumen -> elec (ELEC_EQ.fundicion) -> water.
// Ridge expressed in ORIGINAL feature space: water = intercept + t*trend
//   + elec*elecMWh + vol*Volumen + sin*sin(2pi m/12) + cos*cos(2pi m/12).
export const WATER_CHAIN = {
  intercept: 1594.556585,
  t: 30.893213,
  elec: 0.262595,
  vol: 0.807936,
  sin: 215.219105,
  cos: 299.115121,
  rmse: 357.7,
  mapeMonthly: 5.18,
  mapeQuarterly: 3.22,
};

// 2025 tariffs in $ per stored consumption unit (electricity $/MWHr, water $/M3).
export const TARIFF_2025 = { electricity: 2315.0, water: 30.70 };

// Historical (Volumen -> real consumption) clouds, 48 months 2022-2025.
export const SCATTER = {
  fundicionElec: [{ vol: 1504.4, real: 3841.4 }, { vol: 1554.4, real: 4212.0 }, { vol: 1419.3, real: 4296.6 }, { vol: 985.3, real: 3259.6 }, { vol: 1602.5, real: 4469.0 }, { vol: 1828.8, real: 4808.6 }, { vol: 1826.3, real: 5056.7 }, { vol: 1737.8, real: 4760.8 }, { vol: 1523.1, real: 4253.5 }, { vol: 1884.3, real: 3871.7 }, { vol: 1710.3, real: 4648.2 }, { vol: 667.9, real: 2483.1 }, { vol: 1432.8, real: 4169.1 }, { vol: 1629.7, real: 4230.3 }, { vol: 1899.2, real: 4876.9 }, { vol: 1426.3, real: 4279.7 }, { vol: 1648.6, real: 4668.8 }, { vol: 1599.7, real: 4635.8 }, { vol: 1536.1, real: 4585.1 }, { vol: 1078.3, real: 3382.9 }, { vol: 1427.8, real: 4311.9 }, { vol: 1245.4, real: 3960.7 }, { vol: 1329.8, real: 4035.5 }, { vol: 1495.8, real: 4248.3 }, { vol: 709.1, real: 3207.6 }, { vol: 1662.8, real: 4376.7 }, { vol: 1448.4, real: 4193.0 }, { vol: 1622.9, real: 4252.4 }, { vol: 1486.5, real: 4355.9 }, { vol: 1467.6, real: 4428.0 }, { vol: 1372.0, real: 4260.3 }, { vol: 1203.7, real: 3786.6 }, { vol: 1491.3, real: 4128.8 }, { vol: 1663.1, real: 4475.5 }, { vol: 1639.0, real: 4339.2 }, { vol: 1365.3, real: 3935.2 }, { vol: 540.3, real: 2596.4 }, { vol: 1497.6, real: 4037.5 }, { vol: 1534.4, real: 4338.5 }, { vol: 1408.4, real: 4051.0 }, { vol: 1561.6, real: 4300.2 }, { vol: 1472.3, real: 4257.0 }, { vol: 1633.1, real: 4480.3 }, { vol: 1642.9, real: 4427.8 }, { vol: 1344.8, real: 4170.5 }, { vol: 1720.2, real: 4567.4 }, { vol: 1343.2, real: 4339.2 }, { vol: 1070.8, real: 3465.9 }],
  norteElec: [{ vol: 24928.0, real: 4887.7 }, { vol: 33781.0, real: 4929.0 }, { vol: 38487.0, real: 5343.6 }, { vol: 31086.0, real: 4890.5 }, { vol: 34711.0, real: 5495.5 }, { vol: 37216.0, real: 5825.3 }, { vol: 36095.0, real: 5789.1 }, { vol: 34790.0, real: 5620.2 }, { vol: 40157.0, real: 5526.6 }, { vol: 37265.0, real: 4472.0 }, { vol: 32887.0, real: 4826.0 }, { vol: 19537.0, real: 2712.1 }, { vol: 28868.0, real: 5021.1 }, { vol: 38186.0, real: 5178.1 }, { vol: 42848.0, real: 6060.2 }, { vol: 36630.0, real: 5506.9 }, { vol: 38867.0, real: 5688.9 }, { vol: 28474.0, real: 4576.1 }, { vol: 28689.0, real: 4846.3 }, { vol: 39365.0, real: 5739.1 }, { vol: 35587.0, real: 5382.3 }, { vol: 33716.0, real: 5409.5 }, { vol: 28702.0, real: 4534.0 }, { vol: 17632.0, real: 2853.8 }, { vol: 27276.0, real: 4938.2 }, { vol: 36114.0, real: 5085.1 }, { vol: 32534.0, real: 5123.2 }, { vol: 34431.0, real: 5262.7 }, { vol: 31986.0, real: 4716.5 }, { vol: 26682.0, real: 4109.0 }, { vol: 29833.0, real: 4861.8 }, { vol: 41057.0, real: 5479.8 }, { vol: 35688.0, real: 5089.1 }, { vol: 37844.0, real: 5292.9 }, { vol: 36720.0, real: 4972.0 }, { vol: 17519.0, real: 2681.3 }, { vol: 30101.0, real: 4902.0 }, { vol: 27081.0, real: 4200.9 }, { vol: 29478.0, real: 4514.8 }, { vol: 29071.0, real: 4665.1 }, { vol: 32585.0, real: 4300.2 }, { vol: 33080.0, real: 4961.6 }, { vol: 34338.0, real: 4968.6 }, { vol: 33705.0, real: 5140.1 }, { vol: 31692.0, real: 4764.4 }, { vol: 37049.0, real: 5326.6 }, { vol: 32821.0, real: 4972.0 }, { vol: 24579.0, real: 3967.3 }],
  fundicionWater: [{ vol: 1504.4, real: 3383.0 }, { vol: 1554.4, real: 3711.7 }, { vol: 1419.3, real: 3753.0 }, { vol: 985.3, real: 3539.0 }, { vol: 1602.5, real: 3687.0 }, { vol: 1828.8, real: 3970.9 }, { vol: 1826.3, real: 4923.8 }, { vol: 1737.8, real: 4339.0 }, { vol: 1523.1, real: 4103.0 }, { vol: 1884.3, real: 4876.4 }, { vol: 1710.3, real: 4687.2 }, { vol: 667.9, real: 3074.8 }, { vol: 1432.8, real: 4957.0 }, { vol: 1629.7, real: 4729.4 }, { vol: 1899.2, real: 5304.6 }, { vol: 1426.3, real: 4902.8 }, { vol: 1648.6, real: 4859.0 }, { vol: 1599.7, real: 4622.0 }, { vol: 1536.1, real: 4009.0 }, { vol: 1078.3, real: 3430.3 }, { vol: 1427.8, real: 3838.9 }, { vol: 1245.4, real: 3955.4 }, { vol: 1329.8, real: 3998.6 }, { vol: 1495.8, real: 4707.3 }, { vol: 709.1, real: 4776.5 }, { vol: 1662.8, real: 5406.8 }, { vol: 1448.4, real: 5866.0 }, { vol: 1622.9, real: 5545.7 }, { vol: 1486.5, real: 4888.5 }, { vol: 1467.6, real: 4888.5 }, { vol: 1372.0, real: 3430.6 }, { vol: 1203.7, real: 3894.1 }, { vol: 1491.3, real: 4567.7 }, { vol: 1663.1, real: 4844.8 }, { vol: 1639.0, real: 4874.7 }, { vol: 1365.3, real: 5116.0 }, { vol: 540.3, real: 4502.1 }, { vol: 1497.6, real: 5346.8 }, { vol: 1534.4, real: 5529.4 }, { vol: 1408.4, real: 5142.7 }, { vol: 1561.6, real: 5456.7 }, { vol: 1472.3, real: 5670.8 }, { vol: 1633.1, real: 5726.9 }, { vol: 1642.9, real: 4982.4 }, { vol: 1344.8, real: 4575.9 }, { vol: 1720.2, real: 5451.4 }, { vol: 1343.2, real: 5182.0 }, { vol: 1070.8, real: 4330.0 }],
};
