-- ============================================================================
-- setup_completo.sql — full schema + data for a FRESH, EMPTY Supabase project.
-- Run once in the Supabase SQL Editor. Idempotent (safe to re-run).
-- Anonymized: plants are only 'Fundición Aluminio' and 'Motores Norte'.
-- AUTO-GENERATED by scripts/generate_predictions.py — do not edit by hand.
-- ============================================================================
BEGIN;

-- shared trigger function: bump updated_at on UPDATE -------------------------
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- 1) TABLES ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.plants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.energy_readings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plant_id uuid NOT NULL REFERENCES public.plants(id) ON DELETE CASCADE,
  period date NOT NULL,
  water numeric, gas numeric, electricity numeric,
  water_pred numeric, gas_pred numeric, electricity_pred numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plant_id, period)
);
CREATE INDEX IF NOT EXISTS idx_readings_period ON public.energy_readings(period);
CREATE INDEX IF NOT EXISTS idx_readings_plant ON public.energy_readings(plant_id);

CREATE TABLE IF NOT EXISTS public.unit_costs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  energy text NOT NULL CHECK (energy IN ('water','gas','electricity')),
  cost_per_unit numeric NOT NULL,
  currency text NOT NULL DEFAULT 'MXN',
  effective_from date NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (energy, effective_from)
);

CREATE TABLE IF NOT EXISTS public.model_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plant_id uuid REFERENCES public.plants(id) ON DELETE CASCADE,
  energy text NOT NULL CHECK (energy IN ('water','gas','electricity')),
  model_type text,
  mape_monthly numeric, mape_quarterly numeric, r2 numeric, mae numeric, rmse numeric,
  annual_error numeric, meets_threshold boolean,
  status text NOT NULL DEFAULT 'ready',
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (plant_id, energy)
);

-- 2) ROW LEVEL SECURITY + public policies ------------------------------------
ALTER TABLE public.plants          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.energy_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unit_costs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_metrics   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public read plants" ON public.plants;
DROP POLICY IF EXISTS "public write plants" ON public.plants;
CREATE POLICY "public read plants"  ON public.plants FOR SELECT USING (true);
CREATE POLICY "public write plants"  ON public.plants FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public read readings" ON public.energy_readings;
DROP POLICY IF EXISTS "public write readings" ON public.energy_readings;
CREATE POLICY "public read readings"  ON public.energy_readings FOR SELECT USING (true);
CREATE POLICY "public write readings" ON public.energy_readings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public read unit_costs" ON public.unit_costs;
DROP POLICY IF EXISTS "public write unit_costs" ON public.unit_costs;
CREATE POLICY "public read unit_costs"  ON public.unit_costs FOR SELECT USING (true);
CREATE POLICY "public write unit_costs" ON public.unit_costs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "public read model_metrics" ON public.model_metrics;
DROP POLICY IF EXISTS "public write model_metrics" ON public.model_metrics;
CREATE POLICY "public read model_metrics"  ON public.model_metrics FOR SELECT USING (true);
CREATE POLICY "public write model_metrics" ON public.model_metrics FOR ALL USING (true) WITH CHECK (true);

-- 3) updated_at triggers -----------------------------------------------------
DROP TRIGGER IF EXISTS trg_readings_updated ON public.energy_readings;
CREATE TRIGGER trg_readings_updated BEFORE UPDATE ON public.energy_readings
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS touch_unit_costs ON public.unit_costs;
CREATE TRIGGER touch_unit_costs BEFORE UPDATE ON public.unit_costs
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS trg_model_metrics_updated ON public.model_metrics;
CREATE TRIGGER trg_model_metrics_updated BEFORE UPDATE ON public.model_metrics
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- 4) PLANTS (anonymized, idempotent by name) ------------------------------
INSERT INTO public.plants (name, location, sort_order)
SELECT 'Fundición Aluminio', NULL, 0
WHERE NOT EXISTS (SELECT 1 FROM public.plants WHERE name = 'Fundición Aluminio');
INSERT INTO public.plants (name, location, sort_order)
SELECT 'Motores Norte', NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM public.plants WHERE name = 'Motores Norte');

-- 5) UNIT COSTS -------------------------------------------------------------
INSERT INTO public.unit_costs (energy, cost_per_unit, currency, effective_from, notes)
VALUES
  ('electricity', 2137.0, 'MXN', '2022-01-01', '2.137 $/kWh x1000 -> $/MWHr'),
  ('water', 25.53, 'MXN', '2022-01-01', '$/M3'),
  ('gas', 615.99, 'MXN', '2022-01-01', 'weighted annual avg $/MWHr (Fundicion)'),
  ('electricity', 2134.0, 'MXN', '2023-01-01', '2.134 $/kWh x1000 -> $/MWHr'),
  ('water', 28.1, 'MXN', '2023-01-01', '$/M3'),
  ('gas', 330.09, 'MXN', '2023-01-01', 'weighted annual avg $/MWHr (Fundicion)'),
  ('electricity', 2232.0, 'MXN', '2024-01-01', '2.232 $/kWh x1000 -> $/MWHr'),
  ('water', 29.73, 'MXN', '2024-01-01', '$/M3'),
  ('gas', 322.64, 'MXN', '2024-01-01', 'weighted annual avg $/MWHr (Fundicion)'),
  ('electricity', 2315.0, 'MXN', '2025-01-01', '2.315 $/kWh x1000 -> $/MWHr'),
  ('water', 30.7, 'MXN', '2025-01-01', '$/M3'),
  ('gas', 377.46, 'MXN', '2025-01-01', 'weighted annual avg $/MWHr (Fundicion)')
ON CONFLICT (energy, effective_from) DO UPDATE SET
  cost_per_unit = EXCLUDED.cost_per_unit, notes = EXCLUDED.notes;

-- 6) ENERGY READINGS — Fundición Aluminio (48 months) --------------------
INSERT INTO public.energy_readings
  (plant_id, period, electricity, water, gas, electricity_pred, water_pred, gas_pred)
VALUES
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-01-01', 3841.3575, 3383.0000, 5562.5002, 4242.2531, 4223.1391, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-02-01', 4211.9782, 3711.6613, 5556.4712, 4321.3639, 4382.7342, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-03-01', 4296.6163, 3753.0000, 5504.1107, 4107.6144, 4217.6545, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-04-01', 3259.6299, 3539.0000, 4088.6524, 3420.7789, 3596.7831, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-05-01', 4468.9809, 3687.0000, 5668.4315, 4397.4201, 4204.3951, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-06-01', 4808.6240, 3970.8651, 6630.0892, 4755.4926, 4323.8800, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-07-01', 5056.7353, 4923.8138, 6420.6006, 4751.5685, 4204.0558, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-08-01', 4760.7729, 4339.0000, 6390.0000, 4611.5091, 4059.1235, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-09-01', 4253.5202, 4103.0000, 6014.4400, 4271.7881, 3858.0625, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-10-01', 3871.6630, 4876.4185, 6769.3441, 4843.4412, 4451.6647, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-11-01', 4648.2254, 4687.2138, 6867.4968, 4567.9869, 4447.9762, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2022-12-01', 2483.0780, 3074.7526, 3341.7218, 2918.6098, 3391.8791, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-01-01', 4169.1128, 4957.0000, 6342.4570, 4128.9227, 4506.2339, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-02-01', 4230.3275, 4729.4184, 6223.2953, 4440.5564, 4845.6088, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-03-01', 4876.8859, 5304.6480, 6899.0865, 4866.9854, 5175.4964, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-04-01', 4279.7206, 4902.8414, 6098.4405, 4118.6061, 4507.0410, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-05-01', 4668.8104, 4859.0000, 6521.4040, 4470.3791, 4631.5233, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-06-01', 4635.8220, 4622.0000, 6252.9615, 4392.9646, 4414.3025, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-07-01', 4585.1008, 4009.0000, 6393.9800, 4292.4106, 4219.7670, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-08-01', 3382.8824, 3430.2895, 4671.4955, 3567.8923, 3622.9483, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-09-01', 4311.8743, 3838.8525, 5770.3995, 4121.0816, 4112.2592, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-10-01', 3960.6668, 3955.3651, 5166.1615, 3832.3060, 4040.6033, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-11-01', 4035.4551, 3998.6229, 5583.5872, 3965.8992, 4353.1783, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2023-12-01', 4248.2981, 4707.3294, 6000.3097, 4228.6286, 4775.4656, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-01-01', 3207.6163, 4776.4989, 3797.0324, 2983.8113, 3991.5861, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-02-01', 4376.6771, 5406.7762, 6749.3811, 4492.8245, 5256.7396, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-03-01', 4193.0426, 5865.9919, 6073.2305, 4153.6225, 4994.6638, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-04-01', 4252.4468, 5545.7273, 6240.4559, 4429.7766, 5118.3475, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-05-01', 4355.9318, 4888.4540, 6031.7996, 4213.8261, 4803.8827, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-06-01', 4428.0291, 4888.4540, 6426.5612, 4183.9383, 4623.4082, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-07-01', 4260.2760, 3430.6287, 5754.4634, 4032.7148, 4389.6964, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-08-01', 3786.5632, 3894.0900, 4946.9700, 3766.3727, 4147.1261, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-09-01', 4128.7911, 4567.7073, 5806.5539, 4221.5317, 4560.6429, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-10-01', 4475.4655, 4844.8169, 6253.9734, 4493.2922, 4922.3770, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-11-01', 4339.2273, 4874.7116, 6084.6105, 4455.1380, 5102.1619, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2024-12-01', 3935.2338, 5115.9850, 5055.1208, 4022.1312, 4986.5264, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-01-01', 2596.4072, 4502.0773, 2864.3415, 2716.5515, 4155.6673, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-02-01', 4037.4787, 5346.8001, 5562.2095, 4231.4281, 5425.3541, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-03-01', 4338.4622, 5529.4368, 5480.7379, 4289.6906, 5470.5861, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-04-01', 4051.0478, 5142.7233, 5197.1966, 4090.2637, 5226.5647, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-05-01', 4300.2000, 5456.6928, 5101.0239, 4332.7131, 5266.5212, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-06-01', 4257.0256, 5670.8176, 5088.0183, 4191.4204, 4999.9116, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-07-01', 4480.3350, 5726.9410, 5619.9903, 4445.9243, 5079.8964, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-08-01', 4427.7743, 4982.3592, 5357.9860, 4461.3823, 5055.2056, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-09-01', 4170.4716, 4575.8855, 4883.6146, 3989.7077, 4752.1219, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-10-01', 4567.4409, 5451.3653, 5880.2850, 4583.7479, 5363.0332, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-11-01', 4339.2273, 5182.0390, 6344.6051, 3987.1597, 5111.0534, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), '2025-12-01', 3465.8829, 4330.0449, 3943.2720, 3556.0507, 4996.8853, NULL)
ON CONFLICT (plant_id, period) DO UPDATE SET
  electricity = EXCLUDED.electricity, water = EXCLUDED.water, gas = EXCLUDED.gas,
  electricity_pred = EXCLUDED.electricity_pred, water_pred = EXCLUDED.water_pred,
  gas_pred = EXCLUDED.gas_pred;

-- 6) ENERGY READINGS — Motores Norte (48 months) --------------------
INSERT INTO public.energy_readings
  (plant_id, period, electricity, water, gas, electricity_pred, water_pred, gas_pred)
VALUES
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-01-01', 4887.6700, 2428.0000, 102.6300, 4064.5101, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-02-01', 4928.9700, 2429.1000, 113.2700, 5057.8728, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-03-01', 5343.6100, 2720.0000, 156.1000, 5585.9158, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-04-01', 4890.4900, 2401.0000, 143.7000, 4755.4767, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-05-01', 5495.4600, 2515.0000, 155.3900, 5162.2247, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-06-01', 5825.3000, 2367.5700, 167.4900, 5443.3016, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-07-01', 5789.0900, 2520.0000, 170.2300, 5317.5183, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-08-01', 5620.2200, 2793.0000, 130.0900, 5171.0890, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-09-01', 5526.5700, 2880.0000, 122.1400, 5773.3004, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-10-01', 4472.0200, 3038.6600, 147.1300, 5448.7997, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-11-01', 4826.0000, 2888.9400, 131.4700, 4957.5603, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2022-12-01', 2712.0500, 1777.8000, 62.7300, 3459.6057, NULL, NULL),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-01-01', 5021.1300, 2710.0000, 112.4100, 4506.6031, 2428.0000, 102.6300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-02-01', 5178.1000, 2710.6900, 122.9700, 5552.1417, 2429.1000, 113.2700),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-03-01', 6060.1600, 2795.0500, 133.0200, 6075.2477, 2720.0000, 156.1000),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-04-01', 5506.8800, 2631.5000, 124.1000, 5377.5487, 2401.0000, 143.7000),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-05-01', 5688.9000, 2641.0000, 125.8200, 5628.5543, 2515.0000, 155.3900),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-06-01', 4576.0900, 2375.0000, 112.0100, 4462.3938, 2367.5700, 167.4900),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-07-01', 4846.3100, 2124.0000, 116.9300, 4486.5181, 2520.0000, 170.2300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-08-01', 5739.1000, 2539.0000, 99.2500, 5684.4330, 2793.0000, 130.0900),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-09-01', 5382.3200, 2402.6000, 149.8100, 5260.5175, 2880.0000, 122.1400),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-10-01', 5409.4900, 2641.2100, 136.7500, 5050.5794, 3038.6600, 147.1300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-11-01', 4534.0000, 2127.7700, 120.9800, 4487.9768, 2888.9400, 131.4700),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2023-12-01', 2853.7800, 1290.9100, 30.0200, 3245.8526, 1777.8000, 62.7300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-01-01', 4938.2000, 2348.6300, 90.8700, 4327.9706, 2710.0000, 112.4100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-02-01', 5085.0700, 2736.3400, 81.9400, 5319.6502, 2710.6900, 122.9700),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-03-01', 5123.2500, 2767.3900, 81.9400, 4917.9515, 2795.0500, 133.0200),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-04-01', 5262.6600, 2773.4300, 80.6900, 5130.8069, 2631.5000, 124.1000),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-05-01', 4716.5100, 2460.1900, 85.9300, 4856.4624, 2641.0000, 125.8200),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-06-01', 4108.9900, 2460.1900, 74.3300, 4261.3200, 2375.0000, 112.0100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-07-01', 4861.7500, 2441.5600, 81.6200, 4614.8822, 2124.0000, 116.9300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-08-01', 5479.8400, 2602.4600, 89.8100, 5874.2861, 2539.0000, 99.2500),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-09-01', 5089.1100, 2503.5200, 88.5100, 5271.8503, 2402.6000, 149.8100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-10-01', 5292.9100, 2732.1100, 86.7300, 5513.7672, 2641.2100, 136.7500),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-11-01', 4972.0200, 2711.4600, 81.2100, 5387.6472, 2127.7700, 120.9800),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2024-12-01', 2681.2900, 2034.0000, 85.8100, 3233.1733, 1290.9100, 30.0200),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-01-01', 4902.0000, 2927.9800, 72.2000, 4644.9535, 2348.6300, 90.8700),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-02-01', 4200.9400, 2761.2800, 65.9000, 4306.0903, 2736.3400, 81.9400),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-03-01', 4514.8200, 2898.6900, 82.8600, 4575.0489, 2767.3900, 81.9400),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-04-01', 4665.0700, 2898.0300, 81.2700, 4529.3810, 2773.4300, 80.6900),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-05-01', 4300.2000, 2993.4900, 81.9900, 4923.6740, 2460.1900, 85.9300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-06-01', 4961.5700, 2806.2400, 72.2900, 4979.2162, 2460.1900, 74.3300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-07-01', 4968.5800, 2862.5200, 69.6700, 5120.3717, 2441.5600, 81.6200),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-08-01', 5140.0800, 2738.0900, 70.6900, 5049.3451, 2602.4600, 89.8100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-09-01', 4764.4100, 2636.3300, 69.2200, 4823.4738, 2503.5200, 88.5100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-10-01', 5326.6100, 3065.5800, 72.2000, 5424.5631, 2732.1100, 86.7300),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-11-01', 4972.0200, 2831.4600, 105.5900, 4950.1547, 2711.4600, 81.2100),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), '2025-12-01', 3967.2900, 2909.4400, 90.2300, 4025.3501, 2034.0000, 85.8100)
ON CONFLICT (plant_id, period) DO UPDATE SET
  electricity = EXCLUDED.electricity, water = EXCLUDED.water, gas = EXCLUDED.gas,
  electricity_pred = EXCLUDED.electricity_pred, water_pred = EXCLUDED.water_pred,
  gas_pred = EXCLUDED.gas_pred;

-- 7) MODEL METRICS ---------------------------------------------------------
INSERT INTO public.model_metrics
  (plant_id, energy, model_type, mape_monthly, mape_quarterly, r2, mae, rmse,
   annual_error, meets_threshold, status)
VALUES
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), 'electricity', 'OLS', 2.56, NULL, 0.9312, 100.6, 138.0, -0.32, true, 'ready'),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), 'water', 'Ridge', 5.18, 3.22, 0.366, 262.6, 357.7, -1.61, true, 'ready'),
  ((SELECT id FROM public.plants WHERE name = 'Fundición Aluminio'), 'gas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 'in_progress'),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), 'electricity', 'OLS', 3.05, NULL, 0.7053, 139.9, 211.4, 1.18, true, 'ready'),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), 'water', 'Naive seasonal', 10.8, 10.89, -11.6552, 313.2, 395.6, -10.95, false, 'ready'),
  ((SELECT id FROM public.plants WHERE name = 'Motores Norte'), 'gas', 'Naive seasonal', 14.99, 11.73, -0.6577, 11.3, 13.9, 8.06, false, 'ready')
ON CONFLICT (plant_id, energy) DO UPDATE SET
  model_type = EXCLUDED.model_type, mape_monthly = EXCLUDED.mape_monthly,
  mape_quarterly = EXCLUDED.mape_quarterly, r2 = EXCLUDED.r2, mae = EXCLUDED.mae,
  rmse = EXCLUDED.rmse, annual_error = EXCLUDED.annual_error,
  meets_threshold = EXCLUDED.meets_threshold, status = EXCLUDED.status;

COMMIT;
